### PR TITLE
fix session to loggin with domain without 403

### PR DESCRIPTION
**Pull request by valdergallo**
- set default header

### CODE REVIEW

**Comment by happyraul** [comment]
I'm not sure I see why this should be included as a default header. To me it seems like something too specific to belong in a thin wrapper - it might come as a surprise to users that this header is being set. What do you think @droustchev?

**Comment by droustchev** [comment]
Yeah, I am not too sure why this change would be necessary. @valdergallo, can you elaborate as to why we should be setting a user agent?

**Comment by valdergallo** [comment]
Hi @happyraul and @droustchev :D 

I'm sugesting this PR because, I was making one API in `wpengine` server. And without this header I can't recive anything. I had to use this header in all my `get_posts` to connect with `WP API Rest`

**Comment by haythamlabrini** [comment]
Too old

**Pull request closed without merging**
